export type PracticeKind = 'read' | 'listen' | 'vocab';

export interface PracticeQ {
  id: string;
  kind: PracticeKind;
  level: string;        // 'TOPIK I' | 'TOPIK II'
  prompt: string;       // 문제 지문/질문 (한국어)
  promptEn?: string;    // 지문/질문 영어 (영어 기반 학습자용)
  passage?: string;     // 읽기 지문
  passageEn?: string;   // 읽기 지문 영어
  audio?: string;       // 듣기 스크립트(실제로는 오디오)
  audioEn?: string;     // 듣기 스크립트 영어
  opts: string[];
  answer: number;       // 정답 index
  explain: string;      // 영어 해설 (정답 근거 + 오답 함정)
}

export const KIND_LABEL: Record<PracticeKind, string> = {
  read: '읽기', listen: '듣기', vocab: '어휘',
};
export const KIND_ICON: Record<PracticeKind, string> = {
  read: 'book', listen: 'head', vocab: 'cards',
};

export const PRACTICE: PracticeQ[] = [
  // ── 기존 문항 (id q1~q5 유지) ──────────────────────────────────
  { id: 'q1', kind: 'vocab', level: 'TOPIK I', prompt: '“사과 (sagwa)”의 뜻은 무엇입니까?',
    promptEn: 'What does “사과 (sagwa)” mean?',
    opts: ['apple', 'banana', 'water', 'bread'], answer: 0,
    explain: '사과 = apple (a fruit). The other options are banana, water and bread, none of which match 사과.' },
  { id: 'q2', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '도서관은 오전 9시부터 오후 6시까지 문을 엽니다. 주말에는 문을 닫습니다.',
    passageEn: 'The library opens from 9 a.m. to 6 p.m. It is closed on weekends.',
    opts: ['도서관 운영시간', '도서관 위치', '도서관 회원가입', '도서관 전화번호'], answer: 0,
    explain: 'The notice gives opening and closing hours, so it is about 운영시간 (opening hours). Location, membership and phone number are never mentioned.' },
  { id: 'q3', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '저는 아침에 (   ) 먹어요.',
    passageEn: 'I eat (   ) in the morning.',
    opts: ['밥을', '밥이', '밥은', '밥도'], answer: 0,
    explain: 'The verb 먹어요 (to eat) needs an object, so the object particle -을/를 is required: 밥을. 밥이/밥은/밥도 are subject or topic markers, which do not fit an object.' },
  { id: 'q4', kind: 'listen', level: 'TOPIK I', prompt: '들은 내용과 같은 것을 고르십시오.',
    promptEn: 'Choose the option that matches what you hear.',
    audio: '(여자) 어제 뭐 했어요?  (남자) 친구랑 영화를 봤어요.',
    audioEn: '(Woman) What did you do yesterday?  (Man) I watched a movie with a friend.',
    opts: ['친구와 영화를 봤다', '혼자 영화를 봤다', '책을 읽었다', '운동을 했다'], answer: 0,
    explain: 'The man says 친구랑 영화를 봤어요 — he watched a movie with a friend. Since he was not alone, chose a book or exercised, only the first option matches.' },
  { id: 'q5', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 어서 오세요. 몇 분이세요?  (남자) 두 명이요.',
    audioEn: '(Woman) Welcome. How many people?  (Man) Two.',
    opts: ['식당', '병원', '학교', '은행'], answer: 0,
    explain: 'Asking 몇 분이세요 (how many people?) and answering 두 명이요 is how a restaurant seats guests, so the place is 식당. The other places do not ask about the number of people.' },

  // ══ 읽기 (Reading) — TOPIK I 30문항 ══════════════════════════════
  { id: 'q6', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '은행은 월요일부터 금요일까지 오전 9시부터 오후 4시까지 문을 엽니다. 토요일과 일요일은 쉽니다.',
    passageEn: 'The bank is open Monday to Friday from 9 a.m. to 4 p.m. It is closed on Saturdays and Sundays.',
    opts: ['은행 영업시간', '은행 위치', '은행 전화번호', '은행 직원 수'], answer: 0,
    explain: 'The notice lists the days and hours the bank is open, so it is about 영업시간 (business hours). Location, phone number and staff count are not mentioned.' },
  { id: 'q7', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '지하철에서 노약자석에는 노인, 임산부, 장애인이 앉을 수 있습니다.',
    passageEn: 'On the subway, the priority seats are for the elderly, pregnant women and people with disabilities.',
    opts: ['노약자석 이용 안내', '지하철 요금', '지하철 노선', '지하철 시간표'], answer: 0,
    explain: 'The notice explains who may use the priority seats (노약자석), so it is about seat usage. Fare, route and timetable are not mentioned.' },
  { id: 'q8', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '오늘 점심시간(오전 11시~오후 2시)에 오시면 모든 음식을 20% 할인해 드립니다.',
    passageEn: 'If you come at lunchtime today (11 a.m.–2 p.m.), you get 20% off all food.',
    opts: ['음식 할인', '식당 이전', '새 메뉴 출시', '직원 모집'], answer: 0,
    explain: 'The notice offers a 20% discount (할인) on food during lunchtime, so it is about a food discount. Moving, new menu and hiring are not mentioned.' },
  { id: 'q9', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '저는 어제 친구(   ) 만났습니다.',
    passageEn: 'I met a friend (   ) yesterday.',
    opts: ['를', '가', '은', '의'], answer: 0,
    explain: '만나다 (to meet) takes an object, which needs the object particle -을/를: 친구를. 가(subject), 은(topic) and 의(possessive) do not mark an object.' },
  { id: 'q10', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '주말에 할머니 댁(   ) 갑니다.',
    passageEn: 'I go (   ) my grandmother\'s house on the weekend.',
    opts: ['에', '을', '가', '와'], answer: 0,
    explain: 'The destination of 가다 (to go) is marked with the location particle -에: 댁에. 을(object), 가(subject) and 와(and/with) do not fit a destination.' },
  { id: 'q11', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '오늘은 날씨(   ) 좋습니다.',
    passageEn: 'The weather (   ) good today.',
    opts: ['가', '를', '에', '도'], answer: 0,
    explain: '좋다 (to be good) is a descriptive verb whose subject uses the subject particle -이/가: 날씨가. 를(object), 에(location) and 도(also) do not mark this subject.' },
  { id: 'q12', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '가: 이름이 무엇입니까?\n나: 제 이름은 김민수(   ).',
    passageEn: 'A: What is your name?\nB: My name is Kim Minsu (   ).',
    opts: ['입니다', '있습니다', '입니다만', '입니까'], answer: 0,
    explain: 'A declarative, polite ending is needed: 제 이름은 김민수입니다 (My name is Kim Minsu). 있습니다 means "to exist/have", 입니다만 means "but", and 입니까 is a question ending.' },
  { id: 'q13', kind: 'read', level: 'TOPIK I', prompt: '이 사람의 가족은 모두 몇 명입니까?',
    promptEn: 'How many people are in this person\'s family?',
    passage: '우리 가족은 모두 네 명입니다. 아버지, 어머니, 여동생, 그리고 저입니다. 아버지는 회사원이고 어머니는 선생님입니다.',
    passageEn: 'My family has four people: my father, mother, younger sister and me. My father is an office worker and my mother is a teacher.',
    opts: ['네 명', '세 명', '다섯 명', '여섯 명'], answer: 0,
    explain: 'The passage states 우리 가족은 모두 네 명입니다 (there are four people), so the answer is 네 명 (four). The other numbers are never mentioned.' },
  { id: 'q14', kind: 'read', level: 'TOPIK I', prompt: '지금은 어떤 계절입니까?',
    promptEn: 'What season is it now?',
    passage: '오늘은 날씨가 아주 춥습니다. 하늘에서 눈이 많이 옵니다. 사람들은 두꺼운 옷을 입고 다닙니다.',
    passageEn: 'The weather is very cold today. It snows a lot. People wear thick clothes.',
    opts: ['겨울', '여름', '봄', '가을'], answer: 0,
    explain: 'Cold weather and heavy snow (눈이 많이 옵니다) indicate winter (겨울). Summer, spring and autumn do not match snow and cold.' },
  { id: 'q15', kind: 'read', level: 'TOPIK I', prompt: '이 사람의 취미는 무엇입니까?',
    promptEn: 'What is this person\'s hobby?',
    passage: '저는 주말에 공원에서 그림을 그립니다. 그림을 그리는 것이 아주 재미있습니다.',
    passageEn: 'On weekends I draw pictures in the park. Drawing is very fun.',
    opts: ['그림 그리기', '노래 부르기', '운동하기', '요리하기'], answer: 0,
    explain: 'The person says they draw pictures (그림을 그립니다), so their hobby is 그림 그리기 (drawing). Singing, exercising and cooking are not mentioned.' },
  { id: 'q16', kind: 'read', level: 'TOPIK I', prompt: '이 사람은 주말에 무엇을 할 겁니까?',
    promptEn: 'What will this person do on the weekend?',
    passage: '이번 주말에 친구와 영화를 보러 갈 겁니다. 영화를 본 후에 맛있는 저녁을 먹을 겁니다.',
    passageEn: 'This weekend I will go to see a movie with a friend. After the movie we will eat a delicious dinner.',
    opts: ['영화 보기', '책 읽기', '여행 가기', '등산하기'], answer: 0,
    explain: 'The passage says they will go to watch a movie (영화를 보러 갈 겁니다). Reading, traveling and hiking are not mentioned.' },
  { id: 'q17', kind: 'read', level: 'TOPIK I', prompt: '이 사람은 어디에서 물건을 샀습니까?',
    promptEn: 'Where did this person buy things?',
    passage: '저는 시장에서 과일과 채소를 샀습니다. 사과는 세 개에 천 원이었습니다. 아주 쌌습니다.',
    passageEn: 'I bought fruit and vegetables at the market. Three apples were 1,000 won. It was very cheap.',
    opts: ['시장', '도서관', '병원', '학교'], answer: 0,
    explain: 'The passage says they bought food at the market (시장에서 샀습니다). Library, hospital and school are not where one buys fruit and vegetables.' },
  { id: 'q18', kind: 'read', level: 'TOPIK I', prompt: '다음 중 맞는 문장을 고르십시오.',
    promptEn: 'Choose the correct sentence.',
    opts: ['저는 어제 친구를 만났습니다.', '저는 어제 친구를 만납니다.', '저는 어제 친구를 만날 겁니다.', '저는 어제 친구를 만나고 있습니다.'],
    answer: 0,
    explain: '어제 (yesterday) requires the past tense, so 만났습니다 (met) is correct. 만납니다 (present), 만날 겁니다 (future) and 만나고 있습니다 (progressive) clash with 어제.' },
  { id: 'q19', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '저는 학교에 (   ) 후에 수업을 시작합니다.',
    passageEn: 'I start class after (   ) at school.',
    opts: ['도착한', '출발한', '떠난', '도망간'], answer: 0,
    explain: 'You start class after arriving at school, so 도착한 (arrived) is correct. 출발한 (departed), 떠난 (left) and 도망간 (ran away) describe leaving, not arriving.' },
  { id: 'q20', kind: 'read', level: 'TOPIK I', prompt: '도서관에서 할 수 없는 것은 무엇입니까?',
    promptEn: 'What cannot be done in the library?',
    passage: '도서관에서는 큰 소리로 이야기하면 안 됩니다. 음식도 먹을 수 없습니다.',
    passageEn: 'In the library you must not talk loudly. You cannot eat food either.',
    opts: ['큰 소리로 이야기하기', '책 읽기', '공부하기', '책 빌리기'], answer: 0,
    explain: 'The notice says you must not talk loudly (큰 소리로 이야기하면 안 됩니다). Reading, studying and borrowing books are all allowed.' },
  { id: 'q21', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '감기에 걸렸을 때는 따뜻한 물을 많이 마시고 푹 쉬는 것이 좋습니다. 열이 많이 나면 병원에 가십시오.',
    passageEn: 'When you catch a cold, drink plenty of warm water and rest well. If you have a high fever, go to the hospital.',
    opts: ['감기에 걸렸을 때의 방법', '약국 위치', '병원 예약 방법', '운동 방법'], answer: 0,
    explain: 'The notice gives advice for when you have a cold (감기에 걸렸을 때), so it is about what to do with a cold. Pharmacy, reservation and exercise are not the topic.' },
  { id: 'q22', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '어제 밤에 비(   ) 많이 왔습니다.',
    passageEn: 'It rained (   ) a lot last night.',
    opts: ['가', '를', '에', '의'], answer: 0,
    explain: '비가 오다 (it rains) uses the subject particle -이/가 with 비: 비가. 를(object), 에(location/time) and 의(possessive) do not fit here.' },
  { id: 'q23', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '가: 안녕하세요? 저는 김민수입니다.\n나: 안녕하세요? 저는 박지수(   ).',
    passageEn: 'A: Hello. I am Kim Minsu.\nB: Hello. I am Park Jisu (   ).',
    opts: ['입니다', '있습니다', '입니까', '이에요'], answer: 0,
    explain: 'A polite declarative ending is needed: 저는 박지수입니다 (I am Park Jisu). 있습니다 means "exist/have", 입니까 is a question, and 이에요 is casual — mismatched with the formal 안녕하세요 exchange.' },
  { id: 'q24', kind: 'read', level: 'TOPIK I', prompt: '이 사람은 무엇으로 학교에 갑니까?',
    promptEn: 'How does this person go to school?',
    passage: '버스를 타고 10분쯤 가면 학교에 도착합니다. 지하철보다 버스가 더 편리합니다.',
    passageEn: 'If you take the bus for about 10 minutes you arrive at school. The bus is more convenient than the subway.',
    opts: ['버스', '지하철', '택시', '자전거'], answer: 0,
    explain: 'The passage says they take the bus (버스를 타고), so the answer is 버스. The subway is only compared against; taxi and bicycle are not mentioned.' },
  { id: 'q25', kind: 'read', level: 'TOPIK I', prompt: '김치는 어떤 음식입니까?',
    promptEn: 'What kind of food is kimchi?',
    passage: '김치는 한국의 전통 음식입니다. 한국 사람들은 밥과 함께 김치를 먹습니다. 김치는 조금 맵습니다.',
    passageEn: 'Kimchi is a traditional Korean food. Koreans eat kimchi with rice. Kimchi is a little spicy.',
    opts: ['조금 매운 전통 음식', '아주 단 음식', '차가운 음료', '서양 음식'], answer: 0,
    explain: 'The passage calls kimchi a traditional food (전통 음식) that is a little spicy (조금 맵습니다). It is not sweet, a cold drink, or Western food.' },
  { id: 'q26', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '가: 주말에 (   ) 갑니까?\n나: 할머니 댁에 갑니다.',
    passageEn: 'A: (   ) are you going on the weekend?\nB: I am going to my grandmother\'s house.',
    opts: ['어디', '언제', '누가', '무엇'], answer: 0,
    explain: 'The answer is a place (할머니 댁, grandmother\'s house), so the question word must be 어디 (where). 언제 (when), 누가 (who) and 무엇 (what) do not ask for a place.' },
  { id: 'q27', kind: 'read', level: 'TOPIK I', prompt: '이 사람은 몇 시에 일어납니까?',
    promptEn: 'What time does this person get up?',
    passage: '저는 매일 아침 7시에 일어납니다. 8시에 집에서 나와서 9시까지 회사에 도착합니다.',
    passageEn: 'I get up at 7 a.m. every morning. I leave home at 8 and arrive at work by 9.',
    opts: ['7시', '8시', '9시', '6시'], answer: 0,
    explain: 'The passage says they get up at 7 (7시에 일어납니다). 8 is when they leave home and 9 is when they arrive; 6 is never mentioned.' },
  { id: 'q28', kind: 'read', level: 'TOPIK I', prompt: '이 사람은 내년에 몇 살입니까?',
    promptEn: 'How old will this person be next year?',
    passage: '저는 올해 스물다섯 살입니다. 내년에는 스물여섯 살이 됩니다.',
    passageEn: 'I am 25 years old this year. Next year I will be 26.',
    opts: ['스물여섯 살', '스물다섯 살', '스물네 살', '스물일곱 살'], answer: 0,
    explain: 'The passage says next year they will be 26 (내년에는 스물여섯 살이 됩니다). 25 is this year, and the other ages are not mentioned.' },
  { id: 'q29', kind: 'read', level: 'TOPIK I', prompt: '빈 곳에 알맞은 것을 고르십시오.',
    promptEn: 'Choose the correct word for the blank.',
    passage: '저는 매일 아침에 커피(   ) 마십니다.',
    passageEn: 'I drink coffee (   ) every morning.',
    opts: ['를', '가', '에', '은'], answer: 0,
    explain: '마시다 (to drink) needs an object with -을/를: 커피를. 가(subject), 에(location/time) and 은(topic) do not mark the object of 마시다.' },
  { id: 'q30', kind: 'read', level: 'TOPIK I', prompt: '이 사람이 좋아하는 색은 무엇입니까?',
    promptEn: 'What color does this person like?',
    passage: '제가 가장 좋아하는 색은 파란색입니다. 파란색 하늘을 보면 기분이 좋아집니다.',
    passageEn: 'My favorite color is blue. When I see the blue sky I feel good.',
    opts: ['파란색', '빨간색', '노란색', '초록색'], answer: 0,
    explain: 'The passage says their favorite color is blue (파란색). Red, yellow and green are not mentioned.' },
  { id: 'q31', kind: 'read', level: 'TOPIK I', prompt: '형은 이 사람보다 몇 살이 많습니까?',
    promptEn: 'How much older is the brother than this person?',
    passage: '저에게는 형이 한 명 있습니다. 형은 저보다 두 살 많습니다. 형은 회사에서 일합니다.',
    passageEn: 'I have one older brother. He is two years older than me. He works at a company.',
    opts: ['두 살', '한 살', '세 살', '네 살'], answer: 0,
    explain: 'The passage says the brother is two years older (저보다 두 살 많습니다). The other ages are not mentioned.' },
  { id: 'q32', kind: 'read', level: 'TOPIK I', prompt: '꽃집은 어디에 있습니까?',
    promptEn: 'Where is the flower shop?',
    passage: '약국은 은행 옆에 있습니다. 약국과 은행 사이에 꽃집이 있습니다.',
    passageEn: 'The pharmacy is next to the bank. The flower shop is between the pharmacy and the bank.',
    opts: ['약국과 은행 사이', '약국 안', '은행 뒤', '약국 앞'], answer: 0,
    explain: 'The passage says the flower shop is between the pharmacy and bank (약국과 은행 사이). Inside, behind or in front of are not mentioned.' },
  { id: 'q33', kind: 'read', level: 'TOPIK I', prompt: '무엇에 대한 안내입니까?',
    promptEn: 'What is this notice about?',
    passage: '내일은 학교 행사 때문에 모든 수업을 하지 않습니다. 다음 주부터 다시 수업을 시작합니다.',
    passageEn: 'Tomorrow all classes are cancelled because of a school event. Classes resume next week.',
    opts: ['수업 휴강', '학교 축제', '시험 일정', '입학 안내'], answer: 0,
    explain: 'The notice says classes will not be held (수업을 하지 않습니다), so it is about class cancellation (휴강). Festival, exam schedule and admission are not the topic.' },

  // ══ 듣기 (Listening) — TOPIK I 30문항 ════════════════════════════
  { id: 'q34', kind: 'listen', level: 'TOPIK I', prompt: '들은 내용과 같은 것을 고르십시오.',
    promptEn: 'Choose the option that matches what you hear.',
    audio: '(남자) 내일 같이 영화 볼까요?  (여자) 좋아요. 몇 시에 만날까요?',
    audioEn: '(Man) Shall we watch a movie together tomorrow?  (Woman) Sure. What time shall we meet?',
    opts: ['내일 같이 영화를 볼 것이다', '오늘 영화를 봤다', '영화를 보지 않을 것이다', '혼자 영화를 볼 것이다'], answer: 0,
    explain: 'The man suggests watching a movie together tomorrow and the woman agrees, so they will watch it together tomorrow. The other options contradict the dialogue.' },
  { id: 'q35', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 어디가 아프세요?  (남자) 머리가 아파요.  (여자) 그럼 약을 지어 드릴게요.',
    audioEn: '(Woman) Where does it hurt?  (Man) My head hurts.  (Woman) Then I will prepare medicine for you.',
    opts: ['약국', '식당', '은행', '도서관'], answer: 0,
    explain: 'The woman asks about pain and prepares medicine (약을 지어 드릴게요), which happens at a pharmacy (약국). Restaurants, banks and libraries do not prepare medicine.' },
  { id: 'q36', kind: 'listen', level: 'TOPIK I', prompt: '남자는 주말에 무엇을 할 겁니까?',
    promptEn: 'What will the man do on the weekend?',
    audio: '(여자) 주말에 뭐 할 거예요?  (남자) 친구들과 등산을 가려고 해요.',
    audioEn: '(Woman) What will you do on the weekend?  (Man) I plan to go hiking with my friends.',
    opts: ['등산', '수영', '쇼핑', '공부'], answer: 0,
    explain: 'The man says he plans to go hiking (등산을 가려고 해요). Swimming, shopping and studying are not mentioned.' },
  { id: 'q37', kind: 'listen', level: 'TOPIK I', prompt: '들은 내용과 같은 것을 고르십시오.',
    promptEn: 'Choose the option that matches what you hear.',
    audio: '(남자) 저는 매일 아침 6시에 일어나서 운동을 해요.  (여자) 대단하시네요.',
    audioEn: '(Man) I get up at 6 every morning and exercise.  (Woman) That is impressive.',
    opts: ['남자는 아침에 운동을 한다', '남자는 저녁에 운동을 한다', '남자는 운동을 싫어한다', '남자는 운동을 하지 않는다'], answer: 0,
    explain: 'The man says he exercises every morning (매일 아침 6시에 일어나서 운동을 해요). Evening, disliking exercise and not exercising all contradict him.' },
  { id: 'q38', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 이 책을 일주일 동안 빌리고 싶어요.  (남자) 네, 여기에 이름과 전화번호를 써 주세요.',
    audioEn: '(Woman) I would like to borrow this book for a week.  (Man) Sure, please write your name and phone number here.',
    opts: ['도서관', '식당', '병원', '공항'], answer: 0,
    explain: 'Borrowing a book (책을 빌리다) happens at a library (도서관). Restaurants, hospitals and airports do not lend books.' },
  { id: 'q39', kind: 'listen', level: 'TOPIK I', prompt: '사과 한 개는 얼마입니까?',
    promptEn: 'How much is one apple?',
    audio: '(여자) 이 사과 한 개에 얼마예요?  (남자) 천 원이에요.',
    audioEn: '(Woman) How much is one apple?  (Man) It is 1,000 won.',
    opts: ['천 원', '이천 원', '삼천 원', '오백 원'], answer: 0,
    explain: 'The man says one apple is 1,000 won (천 원이에요). The other prices are not mentioned.' },
  { id: 'q40', kind: 'listen', level: 'TOPIK I', prompt: '여자는 무엇을 사려고 합니까?',
    promptEn: 'What does the woman plan to buy?',
    audio: '(남자) 뭐가 필요하세요?  (여자) 생일 케이크를 사려고 해요.',
    audioEn: '(Man) What do you need?  (Woman) I am going to buy a birthday cake.',
    opts: ['케이크', '빵', '과일', '꽃'], answer: 0,
    explain: 'The woman says she plans to buy a birthday cake (생일 케이크를 사려고 해요). Bread, fruit and flowers are not mentioned.' },
  { id: 'q41', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 여기서 부산까지 기차표 한 장 주세요.  (남자) 몇 시 기차로 드릴까요?',
    audioEn: '(Woman) One train ticket to Busan, please.  (Man) What time train would you like?',
    opts: ['기차역', '버스 정류장', '공항', '지하철역'], answer: 0,
    explain: 'Buying a train ticket (기차표) happens at a train station (기차역). Bus stops, airports and subway stations sell different tickets.' },
  { id: 'q42', kind: 'listen', level: 'TOPIK I', prompt: '두 사람은 지금 무엇을 할 겁니까?',
    promptEn: 'What will the two people do now?',
    audio: '(남자) 배가 너무 고파요.  (여자) 그럼 우리 같이 점심 먹으러 가요.',
    audioEn: '(Man) I am so hungry.  (Woman) Then let us go eat lunch together.',
    opts: ['점심을 먹을 것이다', '운동할 것이다', '잠을 잘 것이다', '공부할 것이다'], answer: 0,
    explain: 'The man is hungry and the woman suggests eating lunch, so they will eat lunch. Exercising, sleeping and studying are not mentioned.' },
  { id: 'q43', kind: 'listen', level: 'TOPIK I', prompt: '들은 내용과 같은 것을 고르십시오.',
    promptEn: 'Choose the option that matches what you hear.',
    audio: '(여자) 어제 친구 생일 파티에 갔어요. 아주 재미있었어요.',
    audioEn: '(Woman) I went to my friend\'s birthday party yesterday. It was a lot of fun.',
    opts: ['여자는 어제 생일 파티에 갔다', '여자는 오늘 생일 파티에 간다', '여자는 생일 파티에 가지 않았다', '여자는 혼자 생일 파티에 갔다'], answer: 0,
    explain: 'The woman says she went to a birthday party yesterday (어제 친구 생일 파티에 갔어요). Today, not going and going alone all contradict her.' },
  { id: 'q44', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 머리를 좀 짧게 잘라 주세요.  (남자) 네, 이쪽으로 앉으세요.',
    audioEn: '(Woman) Please cut my hair a little shorter.  (Man) Okay, please sit here.',
    opts: ['미용실', '병원', '옷 가게', '식당'], answer: 0,
    explain: 'Getting a haircut (머리를 잘라 주세요) happens at a hair salon (미용실). Hospitals, clothing stores and restaurants do not cut hair.' },
  { id: 'q45', kind: 'listen', level: 'TOPIK I', prompt: '두 사람은 몇 시에 만납니까?',
    promptEn: 'What time will the two people meet?',
    audio: '(남자) 내일 몇 시에 만날까요?  (여자) 세 시에 만나요.',
    audioEn: '(Man) What time shall we meet tomorrow?  (Woman) Let us meet at three.',
    opts: ['세 시', '두 시', '네 시', '한 시'], answer: 0,
    explain: 'The woman says to meet at three (세 시에 만나요). The other times are not mentioned.' },
  { id: 'q46', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 이 편지를 한국에 보내고 싶어요.  (남자) 네, 여기에 주소를 써 주세요.',
    audioEn: '(Woman) I want to send this letter to Korea.  (Man) Okay, please write the address here.',
    opts: ['우체국', '은행', '학교', '도서관'], answer: 0,
    explain: 'Sending a letter (편지를 보내다) happens at a post office (우체국). Banks, schools and libraries do not send letters.' },
  { id: 'q47', kind: 'listen', level: 'TOPIK I', prompt: '여자는 무엇을 재미있다고 합니까?',
    promptEn: 'What does the woman find fun?',
    audio: '(남자) 요즘 뭐가 재미있어요?  (여자) 저는 한국 드라마 보는 게 제일 재미있어요.',
    audioEn: '(Man) What is fun these days?  (Woman) Watching Korean dramas is the most fun for me.',
    opts: ['드라마 보기', '영화 보기', '책 읽기', '운동하기'], answer: 0,
    explain: 'The woman says watching Korean dramas is the most fun (한국 드라마 보는 게 제일 재미있어요). Movies, reading and exercise are not mentioned.' },
  { id: 'q48', kind: 'listen', level: 'TOPIK I', prompt: '지금 날씨는 어떻습니까?',
    promptEn: 'What is the weather like now?',
    audio: '(여자) 오늘 날씨가 어때요?  (남자) 아침에는 맑았는데 지금은 비가 와요.',
    audioEn: '(Woman) How is the weather today?  (Man) It was clear in the morning, but now it is raining.',
    opts: ['비가 온다', '맑다', '눈이 온다', '바람이 분다'], answer: 0,
    explain: 'The man says it is raining now (지금은 비가 와요). Clear was only the morning; snow and wind are not mentioned.' },
  { id: 'q49', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 한국행 비행기 표 한 장 주세요.  (남자) 여권을 보여 주세요.',
    audioEn: '(Woman) One airplane ticket to Korea, please.  (Man) Please show me your passport.',
    opts: ['공항', '기차역', '버스 터미널', '호텔'], answer: 0,
    explain: 'Buying a plane ticket (비행기 표) and showing a passport happens at an airport (공항). Train stations, bus terminals and hotels do not sell plane tickets.' },
  { id: 'q50', kind: 'listen', level: 'TOPIK I', prompt: '여자는 주말에 무엇을 할 겁니까?',
    promptEn: 'What will the woman do on the weekend?',
    audio: '(남자) 이번 주말에 뭐 할 거예요?  (여자) 집에서 한국어를 공부할 거예요.',
    audioEn: '(Man) What will you do this weekend?  (Woman) I will study Korean at home.',
    opts: ['한국어를 공부할 것이다', '여행을 갈 것이다', '운동할 것이다', '쇼핑할 것이다'], answer: 0,
    explain: 'The woman says she will study Korean at home (집에서 한국어를 공부할 거예요). Traveling, exercising and shopping are not mentioned.' },
  { id: 'q51', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 이 돈을 저금하고 싶어요.  (남자) 신분증을 보여 주시겠어요?',
    audioEn: '(Woman) I want to deposit this money.  (Man) May I see your ID?',
    opts: ['은행', '우체국', '병원', '백화점'], answer: 0,
    explain: 'Depositing money (돈을 저금하다) and showing ID happens at a bank (은행). Post offices, hospitals and department stores do not take deposits.' },
  { id: 'q52', kind: 'listen', level: 'TOPIK I', prompt: '여자의 취미는 무엇입니까?',
    promptEn: 'What is the woman\'s hobby?',
    audio: '(남자) 취미가 뭐예요?  (여자) 저는 사진 찍는 것을 좋아해요.',
    audioEn: '(Man) What is your hobby?  (Woman) I like taking photos.',
    opts: ['사진 찍기', '그림 그리기', '노래 부르기', '춤추기'], answer: 0,
    explain: 'The woman says she likes taking photos (사진 찍는 것을 좋아해요). Drawing, singing and dancing are not mentioned.' },
  { id: 'q53', kind: 'listen', level: 'TOPIK I', prompt: '티셔츠는 얼마입니까?',
    promptEn: 'How much is the T-shirt?',
    audio: '(여자) 이 티셔츠가 얼마예요?  (남자) 만 원이에요.',
    audioEn: '(Woman) How much is this T-shirt?  (Man) It is 10,000 won.',
    opts: ['만 원', '오천 원', '이만 원', '천 원'], answer: 0,
    explain: 'The man says the T-shirt is 10,000 won (만 원이에요). The other prices are not mentioned.' },
  { id: 'q54', kind: 'listen', level: 'TOPIK I', prompt: '남자는 무엇을 주문했습니까?',
    promptEn: 'What did the man order?',
    audio: '(남자) 여기서 뭐가 제일 맛있어요?  (여자) 김치찌개가 제일 맛있어요.  (남자) 그럼 김치찌개 하나 주세요.',
    audioEn: '(Man) What is the most delicious thing here?  (Woman) The kimchi stew is the most delicious.  (Man) Then one kimchi stew, please.',
    opts: ['김치찌개', '비빔밥', '불고기', '냉면'], answer: 0,
    explain: 'The man orders kimchi stew (김치찌개 하나 주세요). Bibimbap, bulgogi and naengmyeon are not mentioned.' },
  { id: 'q55', kind: 'listen', level: 'TOPIK I', prompt: '여자의 직업은 무엇입니까?',
    promptEn: 'What is the woman\'s job?',
    audio: '(여자) 저는 학생들을 가르치는 일을 해요.  (남자) 아, 선생님이시군요.',
    audioEn: '(Woman) I teach students.  (Man) Ah, so you are a teacher.',
    opts: ['선생님', '의사', '요리사', '운전기사'], answer: 0,
    explain: 'The woman teaches students, and the man says she is a teacher (선생님이시군요). Doctor, cook and driver are not mentioned.' },
  { id: 'q56', kind: 'listen', level: 'TOPIK I', prompt: '수업은 몇 시에 끝납니까?',
    promptEn: 'What time does the class end?',
    audio: '(남자) 수업이 몇 시에 끝나요?  (여자) 네 시에 끝나요.',
    audioEn: '(Man) What time does the class end?  (Woman) It ends at four.',
    opts: ['네 시', '세 시', '다섯 시', '두 시'], answer: 0,
    explain: 'The woman says class ends at four (네 시에 끝나요). The other times are not mentioned.' },
  { id: 'q57', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 열이 많이 나고 머리가 아파요.  (남자) 약을 처방해 드릴 테니 집에서 푹 쉬세요.',
    audioEn: '(Woman) I have a high fever and a headache.  (Man) I will prescribe medicine, so rest well at home.',
    opts: ['병원', '약국', '학교', '회사'], answer: 0,
    explain: 'A doctor prescribes medicine (약을 처방해 드릴 테니), which happens at a hospital (병원). A pharmacy dispenses rather than prescribes; school and office do not diagnose.' },
  { id: 'q58', kind: 'listen', level: 'TOPIK I', prompt: '남자는 무엇을 해야 합니까?',
    promptEn: 'What should the man do?',
    audio: '(남자) 지금 비가 많이 오는데요.  (여자) 그럼 우산을 가지고 나가세요.',
    audioEn: '(Man) It is raining a lot now.  (Woman) Then take an umbrella when you go out.',
    opts: ['우산을 가지고 나간다', '비옷을 버린다', '집에 그대로 있는다', '모자를 쓴다'], answer: 0,
    explain: 'The woman tells him to take an umbrella (우산을 가지고 나가세요). Throwing away a raincoat, staying home and wearing a hat are not said.' },
  { id: 'q59', kind: 'listen', level: 'TOPIK I', prompt: '오늘은 무슨 요일입니까?',
    promptEn: 'What day of the week is today?',
    audio: '(여자) 오늘은 무슨 요일이에요?  (남자) 화요일이에요.',
    audioEn: '(Woman) What day is it today?  (Man) It is Tuesday.',
    opts: ['화요일', '월요일', '수요일', '목요일'], answer: 0,
    explain: 'The man says today is Tuesday (화요일이에요). Monday, Wednesday and Thursday are not mentioned.' },
  { id: 'q60', kind: 'listen', level: 'TOPIK I', prompt: '여기는 어디입니까?',
    promptEn: 'Where is this conversation taking place?',
    audio: '(여자) 이 책을 빌리고 싶은데요.  (남자) 회원증이 있으세요?',
    audioEn: '(Woman) I would like to borrow this book.  (Man) Do you have a membership card?',
    opts: ['도서관', '서점', '학교', '사무실'], answer: 0,
    explain: 'Borrowing a book (책을 빌리다) with a membership card (회원증) happens at a library (도서관). Bookstores sell rather than lend; school and office do not fit.' },
  { id: 'q61', kind: 'listen', level: 'TOPIK I', prompt: '두 사람은 무엇을 선물로 고를 겁니까?',
    promptEn: 'What will the two people choose as a gift?',
    audio: '(남자) 어머니 생신 선물로 뭐가 좋을까요?  (여자) 꽃이 좋을 것 같아요.',
    audioEn: '(Man) What would be a good birthday gift for my mother?  (Woman) Flowers would be nice.',
    opts: ['꽃', '책', '옷', '케이크'], answer: 0,
    explain: 'The woman suggests flowers (꽃이 좋을 것 같아요) as the gift. Book, clothes and cake are not mentioned.' },

  // ══ 어휘 (Vocabulary) — TOPIK 1 필수 어휘 40문항 ══════════════════
  { id: 'q62', kind: 'vocab', level: 'TOPIK I', prompt: '“물 (mul)”의 뜻은 무엇입니까?',
    promptEn: 'What does “물 (mul)” mean?',
    opts: ['water', 'fire', 'milk', 'juice'], answer: 0,
    explain: '물 (mul) means "water". 불 (bul) is fire, 우유 (uyu) is milk and 주스 (juseu) is juice, so water is correct.' },
  { id: 'q63', kind: 'vocab', level: 'TOPIK I', prompt: '“집 (jip)”의 뜻은 무엇입니까?',
    promptEn: 'What does “집 (jip)” mean?',
    opts: ['house, home', 'school', 'store', 'hospital'], answer: 0,
    explain: '집 (jip) means "house / home". 학교 (hakgyo) is school, 가게 (gage) is store and 병원 (byeongwon) is hospital.' },
  { id: 'q64', kind: 'vocab', level: 'TOPIK I', prompt: '“학교 (hakgyo)”의 뜻은 무엇입니까?',
    promptEn: 'What does “학교 (hakgyo)” mean?',
    opts: ['school', 'library', 'park', 'office'], answer: 0,
    explain: '학교 (hakgyo) means "school". 도서관 (doseogwan) is library, 공원 (gongwon) is park and 사무실 (samusil) is office.' },
  { id: 'q65', kind: 'vocab', level: 'TOPIK I', prompt: '“친구 (chingu)”의 뜻은 무엇입니까?',
    promptEn: 'What does “친구 (chingu)” mean?',
    opts: ['friend', 'teacher', 'parent', 'neighbor'], answer: 0,
    explain: '친구 (chingu) means "friend". 선생님 (seonsaengnim) is teacher, 부모님 (bumonim) is parents and 이웃 (iut) is neighbor.' },
  { id: 'q66', kind: 'vocab', level: 'TOPIK I', prompt: '“가족 (gajok)”의 뜻은 무엇입니까?',
    promptEn: 'What does “가족 (gajok)” mean?',
    opts: ['family', 'company', 'country', 'village'], answer: 0,
    explain: '가족 (gajok) means "family". 회사 (hoesa) is company, 나라 (nara) is country and 마을 (maeul) is village.' },
  { id: 'q67', kind: 'vocab', level: 'TOPIK I', prompt: '“사람 (saram)”의 뜻은 무엇입니까?',
    promptEn: 'What does “사람 (saram)” mean?',
    opts: ['person', 'animal', 'plant', 'thing'], answer: 0,
    explain: '사람 (saram) means "person". 동물 (dongmul) is animal, 식물 (singmul) is plant and 물건 (mulgeon) is thing.' },
  { id: 'q68', kind: 'vocab', level: 'TOPIK I', prompt: '“책 (chaek)”의 뜻은 무엇입니까?',
    promptEn: 'What does “책 (chaek)” mean?',
    opts: ['book', 'notebook', 'newspaper', 'letter'], answer: 0,
    explain: '책 (chaek) means "book". 공책 (gongchaek) is notebook, 신문 (sinmun) is newspaper and 편지 (pyeonji) is letter.' },
  { id: 'q69', kind: 'vocab', level: 'TOPIK I', prompt: '“시간 (sigan)”의 뜻은 무엇입니까?',
    promptEn: 'What does “시간 (sigan)” mean?',
    opts: ['time, hour', 'day', 'week', 'year'], answer: 0,
    explain: '시간 (sigan) means "time / hour". 하루 (haru) is day, 주 (ju) is week and 년 (nyeon) is year.' },
  { id: 'q70', kind: 'vocab', level: 'TOPIK I', prompt: '“날씨 (nalssi)”의 뜻은 무엇입니까?',
    promptEn: 'What does “날씨 (nalssi)” mean?',
    opts: ['weather', 'season', 'temperature', 'climate'], answer: 0,
    explain: '날씨 (nalssi) means "weather". 계절 (gyejeol) is season, 온도 (ondo) is temperature and 기후 (gihu) is climate.' },
  { id: 'q71', kind: 'vocab', level: 'TOPIK I', prompt: '“음식 (eumsik)”의 뜻은 무엇입니까?',
    promptEn: 'What does “음식 (eumsik)” mean?',
    opts: ['food', 'drink', 'dessert', 'snack'], answer: 0,
    explain: '음식 (eumsik) means "food". 음료 (eumnyo) is drink, 디저트 (dijeoteu) is dessert and 간식 (gansik) is snack.' },
  { id: 'q72', kind: 'vocab', level: 'TOPIK I', prompt: '“옷 (ot)”의 뜻은 무엇입니까?',
    promptEn: 'What does “옷 (ot)” mean?',
    opts: ['clothes', 'shoes', 'hat', 'bag'], answer: 0,
    explain: '옷 (ot) means "clothes". 신발 (sinbal) is shoes, 모자 (moja) is hat and 가방 (gabang) is bag.' },
  { id: 'q73', kind: 'vocab', level: 'TOPIK I', prompt: '“돈 (don)”의 뜻은 무엇입니까?',
    promptEn: 'What does “돈 (don)” mean?',
    opts: ['money', 'card', 'price', 'bill'], answer: 0,
    explain: '돈 (don) means "money". 카드 (kadeu) is card, 가격 (gagyeok) is price and 계산서 (gyesanseo) is bill.' },
  { id: 'q74', kind: 'vocab', level: 'TOPIK I', prompt: '“병원 (byeongwon)”의 뜻은 무엇입니까?',
    promptEn: 'What does “병원 (byeongwon)” mean?',
    opts: ['hospital', 'pharmacy', 'clinic', 'school'], answer: 0,
    explain: '병원 (byeongwon) means "hospital". 약국 (yakguk) is pharmacy, 의원 (uiwon) is clinic and 학교 (hakgyo) is school.' },
  { id: 'q75', kind: 'vocab', level: 'TOPIK I', prompt: '“가게 (gage)”의 뜻은 무엇입니까?',
    promptEn: 'What does “가게 (gage)” mean?',
    opts: ['store, shop', 'factory', 'bank', 'library'], answer: 0,
    explain: '가게 (gage) means "store / shop". 공장 (gongjang) is factory, 은행 (eunhaeng) is bank and 도서관 (doseogwan) is library.' },
  { id: 'q76', kind: 'vocab', level: 'TOPIK I', prompt: '“공원 (gongwon)”의 뜻은 무엇입니까?',
    promptEn: 'What does “공원 (gongwon)” mean?',
    opts: ['park', 'garden', 'forest', 'playground'], answer: 0,
    explain: '공원 (gongwon) means "park". 정원 (jeongwon) is garden, 숲 (sup) is forest and 놀이터 (noriteo) is playground.' },
  { id: 'q77', kind: 'vocab', level: 'TOPIK I', prompt: '“영화 (yeonghwa)”의 뜻은 무엇입니까?',
    promptEn: 'What does “영화 (yeonghwa)” mean?',
    opts: ['movie', 'drama', 'song', 'play'], answer: 0,
    explain: '영화 (yeonghwa) means "movie". 드라마 (deurama) is drama, 노래 (norae) is song and 연극 (yeongeuk) is play.' },
  { id: 'q78', kind: 'vocab', level: 'TOPIK I', prompt: '“기차 (gicha)”의 뜻은 무엇입니까?',
    promptEn: 'What does “기차 (gicha)” mean?',
    opts: ['train', 'bus', 'car', 'airplane'], answer: 0,
    explain: '기차 (gicha) means "train". 버스 (beoseu) is bus, 자동차 (jadongcha) is car and 비행기 (bihaenggi) is airplane.' },
  { id: 'q79', kind: 'vocab', level: 'TOPIK I', prompt: '“꽃 (kkot)”의 뜻은 무엇입니까?',
    promptEn: 'What does “꽃 (kkot)” mean?',
    opts: ['flower', 'tree', 'grass', 'leaf'], answer: 0,
    explain: '꽃 (kkot) means "flower". 나무 (namu) is tree, 풀 (pul) is grass and 잎 (ip) is leaf.' },
  { id: 'q80', kind: 'vocab', level: 'TOPIK I', prompt: '“바다 (bada)”의 뜻은 무엇입니까?',
    promptEn: 'What does “바다 (bada)” mean?',
    opts: ['sea, ocean', 'river', 'lake', 'pond'], answer: 0,
    explain: '바다 (bada) means "sea / ocean". 강 (gang) is river, 호수 (hosu) is lake and 연못 (yeonmot) is pond.' },
  { id: 'q81', kind: 'vocab', level: 'TOPIK I', prompt: '“하늘 (haneul)”의 뜻은 무엇입니까?',
    promptEn: 'What does “하늘 (haneul)” mean?',
    opts: ['sky', 'cloud', 'star', 'moon'], answer: 0,
    explain: '하늘 (haneul) means "sky". 구름 (gureum) is cloud, 별 (byeol) is star and 달 (dal) is moon.' },
  { id: 'q82', kind: 'vocab', level: 'TOPIK I', prompt: '“먹다 (meokda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “먹다 (meokda)” mean?',
    opts: ['to eat', 'to drink', 'to cook', 'to buy'], answer: 0,
    explain: '먹다 (meokda) means "to eat". 마시다 (masida) is to drink, 요리하다 (yorihada) is to cook and 사다 (sada) is to buy.' },
  { id: 'q83', kind: 'vocab', level: 'TOPIK I', prompt: '“마시다 (masida)”의 뜻은 무엇입니까?',
    promptEn: 'What does “마시다 (masida)” mean?',
    opts: ['to drink', 'to eat', 'to pour', 'to wash'], answer: 0,
    explain: '마시다 (masida) means "to drink". 먹다 (meokda) is to eat, 붓다 (butda) is to pour and 씻다 (ssitda) is to wash.' },
  { id: 'q84', kind: 'vocab', level: 'TOPIK I', prompt: '“가다 (gada)”의 뜻은 무엇입니까?',
    promptEn: 'What does “가다 (gada)” mean?',
    opts: ['to go', 'to come', 'to return', 'to leave'], answer: 0,
    explain: '가다 (gada) means "to go". 오다 (oda) is to come, 돌아오다 (doraoda) is to return and 떠나다 (tteonada) is to leave.' },
  { id: 'q85', kind: 'vocab', level: 'TOPIK I', prompt: '“오다 (oda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “오다 (oda)” mean?',
    opts: ['to come', 'to go', 'to enter', 'to arrive'], answer: 0,
    explain: '오다 (oda) means "to come". 가다 (gada) is to go, 들어가다 (deureogada) is to enter and 도착하다 (dochakhada) is to arrive.' },
  { id: 'q86', kind: 'vocab', level: 'TOPIK I', prompt: '“보다 (boda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “보다 (boda)” mean?',
    opts: ['to see, to watch', 'to hear', 'to touch', 'to smell'], answer: 0,
    explain: '보다 (boda) means "to see / to watch". 듣다 (deutda) is to hear, 만지다 (manjida) is to touch and 냄새 맡다 (naemsae matda) is to smell.' },
  { id: 'q87', kind: 'vocab', level: 'TOPIK I', prompt: '“듣다 (deutda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “듣다 (deutda)” mean?',
    opts: ['to listen, to hear', 'to see', 'to speak', 'to read'], answer: 0,
    explain: '듣다 (deutda) means "to listen / to hear". 보다 (boda) is to see, 말하다 (malhada) is to speak and 읽다 (ikda) is to read.' },
  { id: 'q88', kind: 'vocab', level: 'TOPIK I', prompt: '“읽다 (ikda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “읽다 (ikda)” mean?',
    opts: ['to read', 'to write', 'to listen', 'to speak'], answer: 0,
    explain: '읽다 (ikda) means "to read". 쓰다 (sseuda) is to write, 듣다 (deutda) is to listen and 말하다 (malhada) is to speak.' },
  { id: 'q89', kind: 'vocab', level: 'TOPIK I', prompt: '“쓰다 (sseuda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “쓰다 (sseuda)” mean?',
    opts: ['to write, to use', 'to read', 'to draw', 'to erase'], answer: 0,
    explain: '쓰다 (sseuda) means "to write / to use". 읽다 (ikda) is to read, 그리다 (geurida) is to draw and 지우다 (jiuda) is to erase.' },
  { id: 'q90', kind: 'vocab', level: 'TOPIK I', prompt: '“자다 (jada)”의 뜻은 무엇입니까?',
    promptEn: 'What does “자다 (jada)” mean?',
    opts: ['to sleep', 'to wake up', 'to rest', 'to dream'], answer: 0,
    explain: '자다 (jada) means "to sleep". 일어나다 (ireonada) is to wake up, 쉬다 (swida) is to rest and 꿈꾸다 (kkumkkuda) is to dream.' },
  { id: 'q91', kind: 'vocab', level: 'TOPIK I', prompt: '“일어나다 (ireonada)”의 뜻은 무엇입니까?',
    promptEn: 'What does “일어나다 (ireonada)” mean?',
    opts: ['to get up', 'to sleep', 'to sit', 'to lie down'], answer: 0,
    explain: '일어나다 (ireonada) means "to get up". 자다 (jada) is to sleep, 앉다 (antda) is to sit and 눕다 (nupda) is to lie down.' },
  { id: 'q92', kind: 'vocab', level: 'TOPIK I', prompt: '“크다 (keuda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “크다 (keuda)” mean?',
    opts: ['to be big', 'to be small', 'to be tall', 'to be wide'], answer: 0,
    explain: '크다 (keuda) means "to be big". 작다 (jakda) is small, 높다 (nopda) is tall/high and 넓다 (neolda) is wide.' },
  { id: 'q93', kind: 'vocab', level: 'TOPIK I', prompt: '“작다 (jakda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “작다 (jakda)” mean?',
    opts: ['to be small', 'to be big', 'to be short', 'to be narrow'], answer: 0,
    explain: '작다 (jakda) means "to be small". 크다 (keuda) is big, 짧다 (jjalda) is short and 좁다 (jopda) is narrow.' },
  { id: 'q94', kind: 'vocab', level: 'TOPIK I', prompt: '“좋다 (jota)”의 뜻은 무엇입니까?',
    promptEn: 'What does “좋다 (jota)” mean?',
    opts: ['to be good', 'to be bad', 'to be happy', 'to be sad'], answer: 0,
    explain: '좋다 (jota) means "to be good / to like". 나쁘다 (nappeuda) is bad, 기쁘다 (gippeuda) is happy and 슬프다 (seulpeuda) is sad.' },
  { id: 'q95', kind: 'vocab', level: 'TOPIK I', prompt: '“맛있다 (masitda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “맛있다 (masitda)” mean?',
    opts: ['to be delicious', 'to be salty', 'to be sweet', 'to be spicy'], answer: 0,
    explain: '맛있다 (masitda) means "to be delicious". 짜다 (jjada) is salty, 달다 (dalda) is sweet and 맵다 (maepda) is spicy.' },
  { id: 'q96', kind: 'vocab', level: 'TOPIK I', prompt: '“춥다 (chupda)”의 뜻은 무엇입니까?',
    promptEn: 'What does “춥다 (chupda)” mean?',
    opts: ['to be cold', 'to be hot', 'to be cool', 'to be warm'], answer: 0,
    explain: '춥다 (chupda) means "to be cold". 덥다 (deopda) is hot, 시원하다 (siwonhada) is cool and 따뜻하다 (ttatteuthada) is warm.' },
  { id: 'q97', kind: 'vocab', level: 'TOPIK I', prompt: '“지금 (jigeum)”의 뜻은 무엇입니까?',
    promptEn: 'What does “지금 (jigeum)” mean?',
    opts: ['now', 'yesterday', 'tomorrow', 'today'], answer: 0,
    explain: '지금 (jigeum) means "now". 어제 (eoje) is yesterday, 내일 (naeil) is tomorrow and 오늘 (oneul) is today.' },
  { id: 'q98', kind: 'vocab', level: 'TOPIK I', prompt: '“항상 (hangsang)”의 뜻은 무엇입니까?',
    promptEn: 'What does “항상 (hangsang)” mean?',
    opts: ['always', 'sometimes', 'never', 'often'], answer: 0,
    explain: '항상 (hangsang) means "always". 가끔 (gakkeum) is sometimes, 결코 (gyeolko) is never and 자주 (jaju) is often.' },
  { id: 'q99', kind: 'vocab', level: 'TOPIK I', prompt: '“개 (gae)”의 뜻은 무엇입니까?',
    promptEn: 'What does “개 (gae)” mean?',
    opts: ['counter for objects', 'counter for people', 'counter for animals', 'counter for books'], answer: 0,
    explain: '개 (gae) is the general counter for objects, as in 사과 한 개 (one apple). People use 명 (myeong), animals use 마리 (mari) and books use 권 (gwon).' },
  { id: 'q100', kind: 'vocab', level: 'TOPIK I', prompt: '“에 (e)”의 뜻은 무엇입니까?',
    promptEn: 'What does “에 (e)” mean?',
    opts: ['at / to (location-time particle)', 'object particle', 'topic particle', 'subject particle'], answer: 0,
    explain: '에 (e) marks a location or time, as in 학교에 가다 (go to school) or 3시에 만나다 (meet at 3). Object is 을/를, topic is 은/는 and subject is 이/가.' },
];
