import type { StoryEpisode } from '../types/game';

/**
 * 글로시스: 데뷔 프로젝트 — 스토리 (EP.1~16)
 *
 * 서사: 캄보디아에서 온 대표(=플레이어)가 기획사 '글로시스'를 열고,
 *       아란 → 채아 → 다희 → 로이 순으로 멤버를 영입해 TOPIK I 2급 = 데뷔까지 키운다.
 * 각 화 = TOPIK 핵심 표현 1개. 장면 이미지/영상은 기존 제작 자산을 재사용한다.
 */
export const STORY: StoryEpisode[] = [
  {
    no: 1, member: 'aran',
    titleKo: '첫 걸음, 한글', titleEn: 'First Step: Hangul',
    descKo: '기획사를 열고, 아란이 첫 연습생으로 합류해요',
    descEn: 'The agency opens · Aran joins as the first trainee',
    focusKo: '한글 자음·모음 · 글자 조합', focusEn: 'Hangul consonants & vowels',
    scene: 'assets/ep1/ep1_arrival.jpg',
    face: 'assets/glowsis/aran.webp',
    lines: [
      { who: 'Aran', ko: '…여기가 글로시스 기획사예요?', en: '…Is this the Glowsis agency?' },
      { who: 'Me · CEO', ko: '네, 맞아요. 오늘부터 우리 같이 시작해요!', en: "Yes. Let's start together from today!" },
      { who: 'Aran', ko: '저, 한국어를 잘 못해요… 괜찮아요?', en: "I'm not good at Korean… is that okay?" },
      { who: 'Me · CEO', ko: '괜찮아요. 첫 걸음은 한글이에요. 같이 배워요!', en: "It's okay. The first step is Hangul. Let's learn together!" },
    ],
  },
  {
    no: 2, member: 'chaea',
    titleKo: '만나서 반가워요', titleEn: 'Nice to Meet You',
    descKo: '채아가 합류하고, 자기소개를 연습해요',
    descEn: 'Chaea joins · practicing self-introductions',
    focusKo: '-이에요/예요 · -(으)로 왔어요', focusEn: '-이에요/예요 · came from ~',
    scene: 'assets/chars/chaea.webp',
    face: 'assets/glowsis/chaea.webp',
    lines: [
      { who: 'Chaea', ko: '안녕하세요! 저는 채아예요.', en: "Hello! I'm Chaea." },
      { who: 'Me · CEO', ko: '어서 오세요. 잘 부탁해요.', en: 'Welcome. Nice to have you.' },
      { who: 'Chaea', ko: '저는 캄보디아에서 왔어요. 만나서 반가워요!', en: "I'm from Cambodia. Nice to meet you!" },
      { who: 'Aran', ko: '우리 같이 연습해요!', en: "Let's practice together!" },
    ],
  },
  {
    no: 3, member: 'aran',
    titleKo: '우리의 스케줄', titleEn: 'Our Schedule',
    descKo: '하루 일정을 세우며 시간과 날짜를 배워요',
    descEn: 'Planning the day · time & dates',
    focusKo: '시간·날짜 · -에 · -(으)ㄹ 거예요', focusEn: 'Time & dates · -에 · will',
    scene: 'assets/carousel/aran_daily.jpg',
    face: 'assets/glowsis/aran.webp',
    lines: [
      { who: 'Aran', ko: '대표님, 오늘 연습은 몇 시예요?', en: 'CEO, what time is practice today?' },
      { who: 'Me · CEO', ko: '오전 아홉 시에 시작해요.', en: 'We start at nine in the morning.' },
      { who: 'Chaea', ko: '점심은 어디에서 먹어요?', en: 'Where do we eat lunch?' },
      { who: 'Aran', ko: '내일은 뮤직쇼가 있어요!', en: "There's a music show tomorrow!" },
    ],
  },
  {
    no: 4, member: 'chaea',
    titleKo: '선배 아이돌과', titleEn: 'With a Senior Idol',
    descKo: '선배 아이돌을 만나 인사와 매너를 배워요',
    descEn: 'Meeting a senior idol · greetings & manners',
    focusKo: '높임말 · -님 · 인사 표현', focusEn: 'Polite speech · -님 · greetings',
    scene: 'assets/bg/train.jpg',
    face: 'assets/glowsis/chaea.webp',
    lines: [
      { who: 'Senior', ko: '안녕하세요, 선배예요.', en: "Hello, I'm your sunbae." },
      { who: 'Chaea', ko: '안녕하세요, 선배님! 만나서 영광이에요.', en: 'Hello, sunbae! It is an honor.' },
      { who: 'Senior', ko: '첫인상이 참 좋네요.', en: 'You make a lovely first impression.' },
      { who: 'Aran', ko: '잘 배우겠습니다!', en: "We'll learn a lot from you!" },
    ],
  },
  {
    no: 5, member: 'dahee',
    titleKo: '무대 의상', titleEn: 'Stage Outfit',
    descKo: '댄서 다희가 합류, 무대 의상을 고르러 가요',
    descEn: 'Dancer Dahee joins · shopping for stage outfits',
    focusKo: '옷·색 어휘 · -고 싶어요', focusEn: 'Clothes & colors · want to',
    scene: 'assets/carousel/aran_c_my.jpg',
    face: 'assets/glowsis/dahee.webp',
    lines: [
      { who: 'Dahee', ko: '안녕하세요! 댄서 다희입니다.', en: "Hi! I'm Dahee, your dancer." },
      { who: 'Me · CEO', ko: '다희야, 무대 의상부터 고르자.', en: "Dahee, let's pick your stage outfit first." },
      { who: 'Dahee', ko: '저는 이 핑크 재킷을 입고 싶어요.', en: 'I want to wear this pink jacket.' },
      { who: 'Chaea', ko: '다희가 제일 빛나네요!', en: 'Dahee really shines!' },
    ],
  },
  {
    no: 6, member: 'dahee',
    titleKo: '연습 후 저녁', titleEn: 'Dinner After Practice',
    descKo: '연습이 끝나고 다 같이 저녁을 먹어요',
    descEn: 'Dinner together after practice',
    focusKo: '음식 어휘 · -(으)ㄹ래요? · -아/어 주세요', focusEn: 'Food · shall we? · please do',
    scene: 'assets/carousel/aran_c_daily.jpg',
    face: 'assets/glowsis/dahee.webp',
    lines: [
      { who: 'Dahee', ko: '다들 뭐 먹을래요?', en: 'What does everyone want to eat?' },
      { who: 'Aran', ko: '저는 김치찌개 먹을래요.', en: "I'll have kimchi stew." },
      { who: 'Chaea', ko: '물 좀 주세요!', en: 'Some water, please!' },
      { who: 'Me · CEO', ko: '오늘 연습 잘했어요. 맛있게 먹어요!', en: "Great practice today. Let's eat well!" },
    ],
  },
  {
    no: 7, member: 'roy',
    titleKo: '이사하는 날', titleEn: 'Moving In',
    descKo: '막내 로이가 합류, 새 숙소로 이사해요',
    descEn: 'Maknae Roy joins · moving into the new dorm',
    focusKo: '장소·교통 · -에 가다 · -(으)로', focusEn: 'Places & transport · go by',
    scene: 'assets/hero/campus.webp',
    face: 'assets/glowsis/roy.webp',
    lines: [
      { who: 'Roy', ko: '안녕하세요, 막내 로이예요!', en: "Hi, I'm Roy, the maknae!" },
      { who: 'Me · CEO', ko: '로이야, 숙소는 지하철로 가면 돼.', en: 'Roy, take the subway to the dorm.' },
      { who: 'Roy', ko: '저 상자, 제가 들게요.', en: "I'll carry that box." },
      { who: 'Aran', ko: '로이가 와서 우리 넷이 다 모였어요!', en: 'With Roy, all four of us are here!' },
    ],
  },
  {
    no: 8, member: 'roy',
    titleKo: '합동 무대', titleEn: 'Joint Stage',
    descKo: '선배들과 함께 무대에 서요',
    descEn: 'Sharing the stage with seniors',
    focusKo: '-고 · -(으)면서 (동시 동작)', focusEn: 'And · while doing',
    scene: 'assets/glowsis/story/u2.webp',
    face: 'assets/glowsis/roy.webp',
    lines: [
      { who: 'Senior', ko: '오늘은 우리와 같이 무대에 서요.', en: 'Today we share the stage with you.' },
      { who: 'Roy', ko: '노래하면서 춤도 출 수 있어요?', en: 'Can you sing and dance at the same time?' },
      { who: 'Dahee', ko: '네, 저는 노래하면서 춤춰요.', en: 'Yes, I dance while singing.' },
      { who: 'Me · CEO', ko: '다 같이 멋진 무대를 만들어요!', en: "Let's make a great stage together!" },
    ],
  },
  {
    no: 9, member: 'aran',
    titleKo: '팀 프로젝트', titleEn: 'Team Project',
    descKo: '새 무대를 함께 기획하며 제안해요',
    descEn: 'Planning a new stage together · suggestions',
    focusKo: '-(으)ㄹ까요? · -는 게 어때요?', focusEn: 'Shall we? · how about',
    scene: 'assets/carousel/aran_home.jpg',
    face: 'assets/glowsis/aran.webp',
    lines: [
      { who: 'Aran', ko: '새 곡 컨셉을 정할까요?', en: 'Shall we decide the concept for the new song?' },
      { who: 'Chaea', ko: '여름 콘셉트는 어때요?', en: 'How about a summer concept?' },
      { who: 'Dahee', ko: '저는 시원한 무대가 좋아요.', en: "I'd love a refreshing stage." },
      { who: 'Me · CEO', ko: '좋아요. 다 같이 만들어 봐요.', en: "Great. Let's build it together." },
    ],
  },
  {
    no: 10, member: 'chaea',
    titleKo: '녹음실', titleEn: 'Recording Day',
    descKo: '녹음실에서 능력과 가능을 말해요',
    descEn: 'At the studio · ability & possibility',
    focusKo: '-(으)ㄹ 수 있다/없다', focusEn: 'Can / cannot',
    scene: 'assets/carousel/aran_book.jpg',
    face: 'assets/glowsis/chaea.webp',
    lines: [
      { who: 'Chaea', ko: '이번 파트는 제가 부를 수 있어요!', en: 'I can sing this part!' },
      { who: 'Aran', ko: '저는 높은 음을 못 올라가요.', en: "I can't reach the high notes." },
      { who: 'Me · CEO', ko: '괜찮아요. 천천히 하면 할 수 있어요.', en: "It's okay. Take it slow — you can do it." },
      { who: 'Chaea', ko: '다 같이 할 수 있어요!', en: 'We can all do it!' },
    ],
  },
  {
    no: 11, member: 'dahee',
    titleKo: '컨셉과 스타일링', titleEn: 'Concept & Styling',
    descKo: '무대 콘셉트와 스타일을 정해요',
    descEn: 'Choosing the stage concept & styling',
    focusKo: '색·외모 형용사 · -아/어요', focusEn: 'Colors & looks · descriptive verbs',
    scene: 'assets/carousel/aran_profile_v.jpg',
    face: 'assets/glowsis/dahee.webp',
    lines: [
      { who: 'Dahee', ko: '이번 콘셉트는 어때요?', en: 'What do you think of this concept?' },
      { who: 'Aran', ko: '파란색이 예뻐요.', en: 'The blue looks pretty.' },
      { who: 'Chaea', ko: '저는 밝은 색이 좋아요.', en: 'I like bright colors.' },
      { who: 'Me · CEO', ko: '우리 팀은 핑크가 잘 어울려요.', en: 'Pink suits our team.' },
    ],
  },
  {
    no: 12, member: 'roy',
    titleKo: '콜라보 곡', titleEn: 'Collab Song',
    descKo: '선배와 콜라보 곡으로 음악방송에 나가요',
    descEn: 'A collab song · on the music show',
    focusKo: '-는데 · -지만 (배경·반대)', focusEn: 'Background & contrast',
    scene: 'assets/hero/group_stage.webp',
    face: 'assets/glowsis/roy.webp',
    lines: [
      { who: 'Roy', ko: '무대가 긴장되는데 재미있어요.', en: "I'm nervous on stage, but it's fun." },
      { who: 'Senior', ko: '처음에는 어렵지만 금방 익숙해져요.', en: 'It is hard at first, but you get used to it.' },
      { who: 'Dahee', ko: '관객들이 우리를 응원해요!', en: 'The crowd is cheering for us!' },
      { who: 'Me · CEO', ko: '우리 콜라보, 정말 멋졌어요.', en: 'Our collab was truly amazing.' },
    ],
  },
  {
    no: 13, member: 'aran',
    titleKo: '데뷔 준비', titleEn: 'Debut Prep',
    descKo: '데뷔를 준비하며 이유와 원인을 말해요',
    descEn: 'Preparing for debut · reasons & causes',
    focusKo: '-아/어서 · -기 때문에', focusEn: 'Because / so',
    scene: 'assets/carousel/aran_rank.jpg',
    face: 'assets/glowsis/aran.webp',
    lines: [
      { who: 'Aran', ko: '오늘 열심히 연습해서 피곤해요.', en: "I practiced hard, so I'm tired." },
      { who: 'Chaea', ko: '데뷔하기 때문에 긴장돼요.', en: "I'm nervous because we're debuting." },
      { who: 'Me · CEO', ko: '우리가 노력했기 때문에 여기까지 왔어요.', en: 'We made it here because we worked hard.' },
      { who: 'Aran', ko: '데뷔 무대, 꼭 성공하고 싶어요!', en: 'I really want our debut stage to succeed!' },
    ],
  },
  {
    no: 14, member: 'chaea',
    titleKo: '리허설', titleEn: 'Rehearsal',
    descKo: '마지막 리허설에서 배운 것을 복습해요',
    descEn: 'Final rehearsal · reviewing what we learned',
    focusKo: '관형사형 -(으)ㄴ/는 · 복습', focusEn: 'Modifiers · review',
    scene: 'assets/carousel/aran_c_rank.jpg',
    face: 'assets/glowsis/chaea.webp',
    lines: [
      { who: 'Chaea', ko: '어제 배운 노래를 다시 해요.', en: "Let's do the song we learned yesterday again." },
      { who: 'Dahee', ko: '무대에서 실수한 부분을 고쳐요.', en: "Let's fix the part we missed on stage." },
      { who: 'Me · CEO', ko: '지금까지 배운 것이 다 여기 있어요.', en: "Everything we've learned is right here." },
      { who: 'Chaea', ko: '완벽해요! 이제 준비됐어요.', en: "Perfect! We're ready now." },
    ],
  },
  {
    no: 15, member: 'dahee',
    titleKo: '인터뷰', titleEn: 'Interview',
    descKo: '데뷔 전 인터뷰에서 감정과 각오를 말해요',
    descEn: 'Pre-debut interview · feelings & resolve',
    focusKo: '-네요 · -겠- · 감정 표현', focusEn: 'Expressing feelings',
    scene: 'assets/glowsis/story/u3.webp',
    face: 'assets/glowsis/dahee.webp',
    lines: [
      { who: 'Reporter', ko: '데뷔 소감이 어떠세요?', en: 'How do you feel about debuting?' },
      { who: 'Dahee', ko: '정말 떨리네요. 열심히 하겠습니다!', en: "I'm really nervous. We'll do our best!" },
      { who: 'Aran', ko: '글로시스를 기다려 주신 팬들, 감사합니다.', en: 'Thank you to the fans who waited for Glowsis.' },
      { who: 'Me · CEO', ko: '우리 팀을 믿어 주세요.', en: 'Please believe in our team. ' },
    ],
  },
  {
    no: 16, member: 'all',
    titleKo: '데뷔 무대', titleEn: 'Debut Stage',
    descKo: '드디어 데뷔 — TOPIK I 2급, 그리고 뮤직비디오',
    descEn: 'Finally, debut — TOPIK I level 2 & the music video',
    focusKo: 'TOPIK I 2급 종합 · 데뷔', focusEn: 'TOPIK I level 2 · debut',
    scene: 'assets/hero/group_stage.webp',
    face: 'assets/hero/group_stage.webp',
    lines: [
      { who: 'Aran', ko: '여러분, 드디어 데뷔합니다!', en: "Everyone — we're finally debuting!" },
      { who: 'Chaea', ko: '글로시스, 시작합니다!', en: 'Glowsis, here we go!' },
      { who: 'Me · CEO', ko: '여기까지 온 우리 모두, 정말 수고했어요.', en: 'We all made it here — you worked so hard.' },
      { who: 'Roy', ko: '우리의 무대를 봐 주세요!', en: 'Please watch our stage!' },
    ],
  },
];

/** 특정 화 데이터 */
export const storyByNo = (no: number): StoryEpisode | undefined => STORY.find((e) => e.no === no);
